<?php

require_once dirname(__FILE__) . '/../../../../lib/Autoloader/Simple/MapAutoloaderBuilder.php';

/**
 * Test class for Autoloader_Simple_MapAutoloaderBuilder.
 * Generated by PHPUnit on 2011-09-26 at 15:50:16.
 */
class Autoloader_Simple_MapAutoloaderBuilderTest extends PHPUnit_Framework_TestCase {

    static $testdir;

    protected function setUp() {
        self::$testdir = dirname(__FILE__) . '/../../../testdir';
    }

    /**
     * @test
     */
    function getOutput() {
        $output = Autoloader_Simple_MapAutoloaderBuilder::getOutput(self::$testdir);
        eval(substr($output, strlen('<?php')));
        $expected = array('Foo', 'HogeHoge\\Hoge', 'HogeHoge\\Fuga', 'Foo\\Bar\\Foo_Bar');
        $this->assertSame($expected, array_keys(Autoloader_Simple_MapAutoloader::$_map));
    }

    /**
     * @test
     */
    function getClassNameWithNoClass() {
        $classNames = Autoloader_Simple_MapAutoloaderBuilder::getClassNames(self::$testdir . '/noclass.php');
        $this->assertSame(array(), $classNames);
    }

    /**
     * @test
     */
    function getClassNamesWithSimple() {
        $classNames = Autoloader_Simple_MapAutoloaderBuilder::getClassNames(__FILE__);
        $this->assertSame(array(__CLASS__), $classNames);
    }

    /**
     * @test
     */
    function getClassNameWithNamespace() {
        if (false === defined('T_NAMESPACE')) {
            $this->markTestSkipped('your php version smaller than 5.3');
        }
        $classNames = Autoloader_Simple_MapAutoloaderBuilder::getClassNames(self::$testdir . '/test.php');
        $expected = array(
            'HogeHoge\\Hoge',
            'HogeHoge\\Fuga',
            'Foo\\Bar\\Foo_Bar',
        );
        $this->assertSame($expected, $classNames);
    }

}
